### ISSUE TITLE
Cordova.js will not be added on livereload with Angular 9

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/angular-toolkit#184]
**Summary**

After updating an app to Angular 9, the cordova.js file will not be added anymore on ionic cordova run with livereload.

The app will start without problems, but will not have any cordova context

**Steps to reproduce**

1. Run the following command on Angular 8 app with Ionic: `ionic cordova run android -l`

2. The app is working as expected because it will add the cordova.js (can be checked by enter localhost:8100 and you see it)

3. Upgrade the app to Angular 9 (`ng update @angular/cli @angular/core --next=true`)

4. Run the same command as mentioned in step 1. The cordova.js will NOT be added anymore

At the moment I do not have a clue why this is happening, but tested on three apps after upgrading to Angular 9, so Angular seems to have something changed.

**Workaround**

For the moment, you have to add the cordova.js manually inside the angular.json, e.g. for Android. The same for the assets under platforms/android/platform_www

**Comment by mhartington** [comment]
I don't have an android device to test against right now, but I can see cordova.js being copied over and included in the final build. 


<img width="754" alt="Screen Shot 2020-01-07 at 4 59 00 PM" src="https://user-images.githubusercontent.com/2835826/71932962-01d3a580-316f-11ea-8da3-668a7ef1e13a.png">

<img width="369" alt="Screen Shot 2020-01-07 at 5 03 59 PM" src="https://user-images.githubusercontent.com/2835826/71933268-b40b6d00-316f-11ea-9059-3a3859e7a7f3.png">


There's probably something going on in the list of dep you have for your project that are not getting updated. As Angular 9 is still in RC, it's probably best to not use it for production. We'll be providing an update guide for folks.

**Comment by RomainYoobic** [comment]
I'm facing the same issue with angular 9.0.0rc-10 and @ionic/angular-toolkit 2.1.2.
Spotted the utils function in the angular-toolkit package which adds cordova.js to the assets.

<img width="816" alt="Screenshot 2020-01-23 at 15 07 32" src="https://user-images.githubusercontent.com/53899438/72996293-61c67f00-3df2-11ea-8802-c3c6b0c01d16.png">

Then the serve script does nothing with the returned value, and the arguments are not modified in the function 🤔 

<img width="782" alt="Screenshot 2020-01-23 at 15 11 11" src="https://user-images.githubusercontent.com/53899438/72996522-cb468d80-3df2-11ea-849e-0244cde8a655.png">

Whereas in the build script we take care of the returned value: 

<img width="669" alt="Screenshot 2020-01-23 at 15 14 16" src="https://user-images.githubusercontent.com/53899438/72996702-0a74de80-3df3-11ea-81dd-22b3d6ab9c55.png">


Don't know if it helps or if it's irrelevant but those are my observations so far

**Comment by RomainYoobic** [comment]
I was able to reproduce the missing `cordova.js` script bug on an ionic/angular workspace vanilla repo. [Here it is](https://github.com/RomainYoobic/ionic-workspace), the steps to reproduce are in the `readme.md` 😄

**Comment by mhartington** [comment]
This should be fixed via https://github.com/ionic-team/angular-toolkit/pull/201

Appears that how the previous builder worked should have never really worked.

**Comment by adamduren** [comment]
Experiencing this as well with the following command:

> npm run ng -- run app:ionic-cordova-serve --platform=browser

Any timeline on getting a new version out there? Currently blocking our Ionic 5 upgrade.

**Comment by kyoz** [comment]
I'v updated to lastest Ionic and Angular but still having problem (cordova_not_available) when using cordova plugins. Seem to wait for next angular release. :smiley_cat:

**Comment by paulstelzer** [comment]
@kyoz You do not need to wait for next angular release. The reason it's not working is because @ionic/angular-toolkit has not released with the fix https://github.com/ionic-team/angular-toolkit/pull/201 yet. You have to wait until they release the next version or you build it by your own

**Comment by pablomaurer** [comment]
So @ionic/angular-toolkit 2.2.0 was released, but i'm still facing this issue, anybody else?

**Comment by mhartington** [comment]
@pablomaurer I just tested everything with a fresh project and was not able to replicate any issue. Please provide a demo project to look at an open a new issue.

**Comment by adamduren** [comment]
The latest worked for me. The only issue I ran into is I did not have the latest version of `@angular-devkit/architect`. One I upgraded to `@angular-devkit/architect@~0.900.2` all was well.

**Comment by paulstelzer** [comment]
For me it's working without problems with angular 9

**Comment by pablomaurer** [comment]
Yeah, seems to work i could track my remaining problem down to the @ionic-native/core package. Will open there an issue, thanks!
